name: Build AS-Clang-Format

on:
  workflow_dispatch: # 这行保证了你会看到 "Run workflow" 按钮

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure CMake
        run: |
          cmake -S llvm -B build -G "Visual Studio 17 2022" `
            -DLLVM_ENABLE_PROJECTS="clang" `
            -DCMAKE_BUILD_TYPE=Release `
            -DLLVM_USE_CRT_RELEASE="MT" `
            -DLLVM_INCLUDE_TESTS=OFF `
            -DLLVM_INCLUDE_BENCHMARKS=OFF `
            -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded"

      - name: Build
        run: cmake --build build --target clang-format --config Release

      # 新增：把生成的 exe 改名为你想要的名字，方便区分
      - name: Rename EXE
        run: ren build\Release\bin\clang-format.exe as-clang-format.exe

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: as-clang-format-windows
          # 注意：现在路径变到了根目录或 build 目录下，取决于 ren 的执行位置
          # 最保险的写法是直接指向重命名后的文件
          path: build/Release/bin/as-clang-format.exe
