name: Build AS-Clang-Format

on:
  workflow_dispatch: # 这行保证了你会看到 "Run workflow" 按钮

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure CMake
        run: |
          cmake -S llvm -B build -G "Visual Studio 17 2022" `
            -DLLVM_ENABLE_PROJECTS="clang" `
            -DCMAKE_BUILD_TYPE=Release `
            -DLLVM_USE_CRT_RELEASE="MT" `
            -DLLVM_INCLUDE_TESTS=OFF `
            -DLLVM_INCLUDE_BENCHMARKS=OFF

      - name: Build
        run: cmake --build build --target clang-format --config Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: as-clang-format-windows
          path: build/Release/bin/clang-format.exe
